# -----------------------------------------------------------------------------------------------------------------------
# Below is code generated by Code Interpreter.
# This code is prone to truncated results because pandas shows only the first 50 characters of a column value by default.
# -----------------------------------------------------------------------------------------------------------------------

import pandas as pd

# Load the CSV file into a DataFrame for easier manipulation
df = pd.read_csv(file_path)

# Display the first few rows of the DataFrame to find Tina's favorite city
df.head()
